services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://bloguser:password@postgres:5432/blogdb
      - JWT_SECRET=dev-jwt-secret-key
      - JWT_EXPIRES_IN=24h
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=admin123
      - PORT=3001
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - blog-database_default
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

networks:
  blog-database_default:
    external: true